/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hulist.gui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextPane;

/**
 *
 * @author Aleksander
 */
public class DropdownContentsPanel extends javax.swing.JPanel {

    private MainWindow mw;
    
    /**
     * Creates new form DropdownContentsPanel
     */
    public DropdownContentsPanel(MainWindow mw) {
        this.mw = mw;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        textPane = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaMonths = new javax.swing.JTextArea();
        labelTextAreaMonthsHelper = new javax.swing.JLabel();
        buttonClearTextArea = new javax.swing.JButton();
        buttonResetTextAreaMonths = new javax.swing.JButton();
        labelResults = new javax.swing.JLabel();
        labelMonthsRange = new javax.swing.JLabel();

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setViewportView(textPane);

        textAreaMonths.setColumns(20);
        textAreaMonths.setRows(5);
        jScrollPane1.setViewportView(textAreaMonths);
        textAreaMonths.setLineWrap(true);
        textAreaMonths.setWrapStyleWord(true);

        labelTextAreaMonthsHelper.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTextAreaMonthsHelper.setText("?"); // NOI18N

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle(MainWindow.BUNDLE); // NOI18N
        buttonClearTextArea.setText(bundle.getString("DropdownContentsPanel.buttonClearTextArea.text")); // NOI18N
        buttonClearTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearTextAreaActionPerformed(evt);
            }
        });

        buttonResetTextAreaMonths.setText(bundle.getString("DropdownContentsPanel.buttonResetTextAreaMonths.text")); // NOI18N
        buttonResetTextAreaMonths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetTextAreaMonthsActionPerformed(evt);
            }
        });

        labelResults.setText(bundle.getString("DropdownContentsPanel.labelResults.text")); // NOI18N

        labelMonthsRange.setText(bundle.getString("DropdownContentsPanel.labelMonthsRange.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelResults)
                    .addComponent(buttonClearTextArea)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMonthsRange)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTextAreaMonthsHelper))
                    .addComponent(buttonResetTextAreaMonths))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelResults)
                    .addComponent(labelMonthsRange))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonClearTextArea)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTextAreaMonthsHelper)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonResetTextAreaMonths))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonClearTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearTextAreaActionPerformed
        this.textPane.setText("");
    }//GEN-LAST:event_buttonClearTextAreaActionPerformed

    private void buttonResetTextAreaMonthsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetTextAreaMonthsActionPerformed
        textAreaMonths.setText(mw.getDefaultMonths());
    }//GEN-LAST:event_buttonResetTextAreaMonthsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClearTextArea;
    private javax.swing.JButton buttonResetTextAreaMonths;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelMonthsRange;
    private javax.swing.JLabel labelResults;
    private javax.swing.JLabel labelTextAreaMonthsHelper;
    private javax.swing.JTextArea textAreaMonths;
    private javax.swing.JTextPane textPane;
    // End of variables declaration//GEN-END:variables

    public JTextPane getTextPane() {
        return textPane;
    }

    public JButton getButtonClearTextArea() {
        return buttonClearTextArea;
    }

    public JButton getButtonResetTextAreaMonths() {
        return buttonResetTextAreaMonths;
    }

    public JLabel getLabelMonthsRange() {
        return labelMonthsRange;
    }

    public JLabel getLabelResults() {
        return labelResults;
    }

    public JLabel getLabelTextAreaMonthsHelper() {
        return labelTextAreaMonthsHelper;
    }

    public JTextArea getTextAreaMonths() {
        return textAreaMonths;
    }

    
}
